---
- name: put repos file
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: import rpm key
  rpm_key: state=present key=http://nginx.org/keys/nginx_signing.key

- name: install
  yum: name=nginx state=present

- name: put conf files
  copy: src={{ item }} dest=/etc/nginx/{{ item }}
  with_items:
    - nginx.conf
    - conf.d/default.conf

- name: start server
  service: name=nginx state=started enabled=yes
